[mongodb]
mongodb.vikaskonda.in
[catalogue]
catalogue.vikaskonda.in
[redis]
redis.vikaskonda.in
[user]
user.vikaskonda.in
[cart]
cart.vikaskonda.in
[frontend]
frontend.vikaskonda.in
[mysql]
mysql.vikaskonda.in
[shipping]
shipping.vikaskonda.in
[rabbitmq]
rabbitmq.vikaskonda.in
[payment]
payment.vikaskonda.in